### ISSUE TITLE
Use git-crypt for secrets

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/data8xhub#15]
Currently our secrets are uncommitted. Instead, we should be using git-crypt...

**Comment by yuvipanda** [comment]
Done!

**Comment by consideRatio** [comment]
I learned about git-crypt through your repos earlier =D Now i learned about github projects!

I extracted all sensitive information from my values.yaml files into a secret-values.yaml file that I pass to my helm upgrade every time i upgrade, and only this file is git-crypted.

Hmmm, I wonder if you can import values from secret-values automatically from within values.yaml or similar... Using requirements.yaml ? Do i need to publish a helm chart? [Related merged Helm PR](https://github.com/kubernetes/helm/pull/2112/files)

```yaml
    ### cookieSecret OVERRIDDEN in secret-values.yaml
    cookieSecret:
```
