### ISSUE TITLE
Whitelist HTTP proxies that users need to use

### ISSUE THREAD

**Issue by yuvipanda** [berkeley-dsep-infra/data8xhub#21]
Some of the content we use makes calls to external websites. These will be blocked per #11. We need to whitelist some domains through a HTTPS proxy.

**Comment by yuvipanda** [comment]
Might put a bandwidth limit on this.

**Comment by yuvipanda** [comment]
@wiltonwu can you give me a list in the next few days? Would be highly appreciated, thanks!

**Comment by wiltonwu** [comment]
Hey Yuvi, sorry for the deplay but here's that whitelist.  Most of these links are used as hyperlinks, but there are some that are used to display images or passed into the `IPython.display` functions.

Note in lab 03, I link `http://localhost:8888/notebooks/lab03/` to show a csv file in the directory.  If this is a problem, I can take it out.

### Data 8 Links
http://data8.org/
https://www.inferentialthinking.com/

### hyperlinks
http://press.endocrine.org/doi/full/10.1210/jcem.86.9.7875?ck=nck&
https://en.wikiquote.org/wiki/Yuri_Gagarin
https://docs.python.org/3/library/stdtypes.html#string-methods
http://stackoverflow.com/
http://avalon.law.yale.edu/18th_century/rightsof.asp
https://en.wikipedia.org/wiki/Radian
http://www.numpy.org/
http://www.ncdc.noaa.gov/qclcd/QCLCD?prior=N
http://www.census.gov/population/international/data/worldpop/table_population.php
http://edoceo.com/utilitas/csv-file-format
https://apps.ams.usda.gov/FarmersMarketsExport/ExcelExport.aspx
http://spreadsheets.latimes.com/california-ceo-compensation/
https://www.sec.gov/answers/proxyhtf.htm
http://www.pewresearch.org/fact-tank/2015/06/08/scientists-more-worried-than-public-about-worlds-growing-population/ft_15-06-04_popcount/
https://en.wikipedia.org/wiki/International_Organization_for_Standardization
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#Current_codes
http://blogs.worldbank.org/opendata/what-does-life-expectancy-birth-really-mean
https://www.measureevaluation.org/prh/rh_indicators/specific/fertility/total-fertility-rate
https://www.gapminder.org/videos/reducing-child-mortality-a-moral-and-environmental-imperative
http://www.un.org/sustainabledevelopment/poverty/
https://goo.gl/lPujuh
https://www.gapminder.org/videos/dont-panic-end-poverty/

### embedded images
http://imgs.xkcd.com/comics/future_self.png
http://imgs.xkcd.com/comics/e_to_the_pi_minus_pi.png
http://mathworld.wolfram.com/images/eps-gif/TrigonometryAnglesPi4_1000.gif
http://www.pewresearch.org/fact-tank/2015/06/08/scientists-more-worried-than-public-about-worlds-growing-population/ft_15-06-04_popcount/

### Used in`IPython.display` functions
https://www.youtube.com/watch?v=U7db6ZeLR5s (IPython.display.YouTubeVideo)
https://docs.google.com/presentation/d/1urkX-nRsD8VJvcOnJsjmCy0Jpv752Ssn5Pphg2sMC-0/embed?start=false&loop=false&delayms=3000 (IPython.display.IFrame)
https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/David_-_The_Death_of_Socrates.jpg/1024px-David_-_The_Death_of_Socrates.jpg (IPython.display.Image)

**Comment by yuvipanda** [comment]
This was also done. We used sniproxy instead of whitelisting HTTP websites. This means we only allow https websites.
